sudo: false
matrix:
  fast_finish: true
  include:
  - python: 3.5.3
    env: TOXENV=py35
  - python: '3.6'
    env: TOXENV=py36
  - python: '3.7'
    env: TOXENV=py37
    dist: xenial
    sudo: true
cache:
  directories:
  - "$HOME/.cache/pip"
language: python
install: pip install -U tox-travis
script: travis_wait 30 tox --develop
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: awarecan
  password:
    secure: kRTTQLaeg6fVtreXbP1Rk+wgBajrzCb/XSxyDqHthHFMBUZhu6BuxyrXCWTRyNxF/c9Hx41HIf8NK7VoMwsJaZgdJ6e/u138lfmvtSR+nIQaCRf3l9PDZ0YxsJ5ePZZPRS23OH6oPLidPhLAB+I/PlW23Y4zC/bW1Ts0uKXJpcv8S8q9rePgR5dn4X8AuxnvOvTgaAUxw1GratfdNQin1j37g8gW6zrNrGpWii+72x0D85LQO4/HKsRa4jR4ZUipiIzkggySAAdEseHIyiLWKQN002WcZbzRZ2xLR48ZGn0FUMakKRmAENc5LqerZyWPeF+cT8Vwmi2NbE2CucPvnFJDBu9jrddCkX92nAGs3kZSNP0pfzsgWddn0UwBPr+a2MaHksezgXwySmDojUWzqoYSvRQxqLyIg/ur03CIaanwK9uBv3PmQgaHcrqXMHyi49utEigWCqYC33cToeJwyof4xBjGDtDdLl75J0uyWecdTYux+Vedg6iQjie20KTxeO+TQh7sj/4CSSUBRNOxhB0zISlJSLRddmN+H4D2My6op2sfC7ZsyJ6LXuqkbrF4TY8XwdruHbCGbyjIE4FcqJyPi7kwYTWqtzrAYowBMRhZjDP/6OYewcuhIYPOFLszWZ2IyOWfzvpZP8jCJpt4e2xvmZsMl7ifV5wzxyDdzX0=
  on:
    tags: true
    repo: rtfol/aiohttp-sse-client
    python: 3.6
