sudo: false
matrix:
  fast_finish: true
  include:
  - python: 3.5.3
    env: TOXENV=py35
  - python: '3.6'
    env: TOXENV=py36
  - python: '3.7'
    env: TOXENV=py37
    dist: xenial
    sudo: true
cache:
  directories:
  - "$HOME/.cache/pip"
language: python
install: pip install -U tox-travis
script: travis_wait 30 tox --develop
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: awarecan
  password:
    secure: XhIAvIDuN3jPk2UNxt+1ygJd2RSTzjE/HoPJ+6ogLo18wPNCRdcDHqEJ64cqMrwLg+EUNfRk7l3Cum158ILMtVURb0RwsdICjAXv/1xuUy6EWM10iNGqyjUwwey60gxq5fd8OAFSmZwPYPD/aRB2y9MyHuZ6/PBQDeAIyXqhynQEpnRVX9Aefs+Ai6q/nG3yoz5T0sdJPYTomqixGegtjAwQM6KmzJr9YlWDwx0JdhHSTk8ADChr9rw3Y25gHld9QsicdIhh2oe95YtlcR8M2oMUa8/GLGX7VGl4SHneOI0xTnB2lvG+fxyH3acnyzuqhgNSuBSGp6E5QZOjiGGmcA1l2adjLSwy2hcpTZfHiWjcG/FtEGDX+TEcICo3RR4M+1KvVUVplzJ3uS2adTumHP+HyyR2ITYt2QgAxYvO6/Y2eFYKw2xyS7V8V23LueA+zSOB/mhO9EGNl/S14tNimJOTtwNeFBAciVlGrqbALAf5/Sj928ZMqoGyNY0tvtjpf0zIpCARzcy/3RHsRv4uxfDO2rqI8rwhdudkZc4Yrd2S/VHy1si82oEJU4s/oy0pOQTmtMgDb6YU9jw3B2FzVx0No8kCp01Jpvm0lCgAFBMKXPmC3rHukrWkfPcAz3qBWaH44i63TvykRszin/aJWAvfWfJwRluGexFAsVLQQNc=
  on:
    tags: true
    repo: rtfol/aiohttp-sse-client
    python: 3.6
