sudo: false
matrix:
  fast_finish: true
  include:
  - python: 3.5.3
    env: TOXENV=py35
  - python: '3.6'
    env: TOXENV=py36
  - python: '3.7'
    env: TOXENV=py37
    dist: xenial
    sudo: true
cache:
  directories:
  - "$HOME/.cache/pip"
language: python
install: pip install -U tox-travis
script: travis_wait 30 tox --develop
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: awarecan
  password:
    secure: sqYufT0iDx2yLWSEd6FtKKrRCm4VrIHbsrYj2ocUrpjysn/q48TV6x+aiXchFMMZRlg1bCfbl1Y+zgacEJVGPoHE69JVGaCGPHmeei2Q2Ywg44YYB9jbWWPaNWduqNbTKlZMrT5ZLvVS4+A/qbsvsTADnznThf9SlEG2rYJPBek/jBP8H8PSJrJVUqTzI4VR8MbEw4ILik2K8UWo2hPAHV30Io6um/iNuKe6MkMXt36f53dG3C8pAsrvAhdec9pfZ5HNLNlszzFPvgjA20qZzAGEk6swct6piH/Eq6iyHOdEnIYLjI92j4cd6bZkq0DiaZpBZbyQjyD3c82kHdeuV5E7Ed2kYqDUcBdkCF3/LmB6q7W+fMBuuJDN8mosrTU10vVPSDUK1j9Ux80SnjBQt3vyIA3s3m4hEdexTgHGSMuy6QKrHQYOiHv6Utg5EiJvNnQ3V4X7KuLVbJP+6YGd1jYabDcTNWAVNI8IUp96eK/CskhjI589M3G2rn8/u7ufT8LRLYFca9QVbTYtVIWcOUEjKn8WX+uOHncozp5sIw9570xxWMoRuWJFaLL5kWmuN0pTarc7WJIMhkOXhSsHS4n6lgqoNFZQUCWQkozQuo3mxcGMTBRn2oPqu3Z+s2mdB22AqDjH6jL8kvatyw2jlKNXJSR+TX1yq9+1k1LXCiU=
  on:
    tags: true
    repo: rtfol/aiohttp-sse-client
    python: 3.6
