sudo: false
matrix:
  fast_finish: true
  include:
  - python: 3.5.3
    env: TOXENV=py35
  - python: '3.6'
    env: TOXENV=py36
  - python: '3.7'
    env: TOXENV=py37
    dist: xenial
    sudo: true
cache:
  directories:
  - "$HOME/.cache/pip"
language: python
install: pip install -U tox-travis
script: travis_wait 30 tox --develop
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: awarecan
  password:
    secure: xPwNQ4gVb2yI7aSYbzQqiuoUtkR10q/Gsd6g7CzA9xtwurwyUoUjpW+ic611NK5/ZaPGMCKlUe+MszZEGt4XMuWdjxQ3kaaXdhk2+YoR/ixHfkVjGI1LstEiM7EeoKlX6s6YIQ+/mv7qLU2FfM3D5Vx9iYo3kgyNA4Csplpos9XoKcNhwK8fArYiITtG/hDCT/5ykZSJw0IlcaQJy+umPIxLalJVXA4YNA18UuVLqiHyrjTH07IZ1lsycgqb4DyNL8yt1g0NgMHlwsdWENGYV6utbtALIOYq5eV6gVh1FWMT/yGLBLx5BMKa2FioDw2PUl1rvsYH7Oyk6ZBIK17zbwgnunxCTUyOOvY8s4AblESIqeNibCN5xZ+LZvTTNGOtlc6QAXkSjm9yI6knQMY8eWIslNb1SQBMs0PrYFtIJ2KVbm2Ljwa/rARVFF0DoEytA+sM4cXPMpFMaRIP7FRim6Qesn6QhSZ3aVSTsSZ99Ou/WIauS0Jey/bSUkjdpam+/TCyeEQRaVPY3cfSOoQy6l8SM9ibVc3W23DmcaZ3TN2Lu/4fQnCW4VLCZJCW44lal3ab21agLUCtHlCQid7N/fyDSeMOHf2aSoBUP6uJhSgNO7PlMHv/EEG3KsdTQ8oAw2ShsYGrA1TC4APEHIb9m158qkhkVYlBF4vkKy/9Gz8=
  on:
    tags: true
    repo: rtfol/aiohttp-sse-client
    python: 3.6
