sudo: false
matrix:
  fast_finish: true
  include:
  - python: 3.5.3
    env: TOXENV=py35
  - python: '3.6'
    env: TOXENV=py36
  - python: '3.7'
    env: TOXENV=py37
    dist: xenial
    sudo: true
cache:
  directories:
  - "$HOME/.cache/pip"
language: python
install: pip install -U tox-travis
script: travis_wait 30 tox --develop
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: awarecan
  password:
    secure: RElGlTbnqGigPbjBgrQn+09i5RCLrKzfqZa4D5wHu6h9nsJK1VhED+8aP1vKnlTvSaCT6uVLtUh7YzKPTWiBtSWOzNzn6jduvmbeHhL6Jm1Rm1BoeMSInhoeRkSUdl+nyu1IShnbUX1h/RvjoDyKSAc95g4RiIzohpofPUxpkzMlep+qP1MipDqEXqUrQOP0Ktwfx1YMJtaBcFdk8+YcrNYJBDKeo3XVsBfYtnUCGggKLfBv2smRJ+OWuo+RHTCnn2MJCIi44Gp6xXlg7M7WupuMhOEuHmXKmrNi0rFcaasUwRheQMfZYfHDmbvCzRc2bKkxQlU5FPL2iG5uMi4RIC5byaXpUlXuIOLUxIZS78z1dEXpsdDCP0M/z9l/Vq7ztvQTx+8dZO1cq3zwVBjxMvNJIlEY/94kaXqZBVFSbIrDsffFHw6BlI+vT/Vuv5FZEMGz0AdQW7Hy8GUdpLdR8uM4yVNgs6Tl5xIJZsRH9tpcAvxQAhSHYbGFca0jTfrRAU8ROMNCqHdqNyn46Z3nbdST31CnI1NDYKhEeZq/x5+kGh1fjoY+ZytaNtX8OiFjHZfN7j5tAFmjwlipITrFpM+fD5VDNF0B7UNOx1iMkNd3JH8dyBF92t2h6RMtUUtpGOEC6ugGkvsqxVRhmGKZog/Sx2qOE07pEtajkFYpIy0=
  on:
    tags: true
    repo: rtfol/aiohttp-sse-client
    python: 3.6
