sudo: false
matrix:
  fast_finish: true
  include:
  - python: 3.5.3
    env: TOXENV=py35
  - python: '3.6'
    env: TOXENV=py36
  - python: '3.7'
    env: TOXENV=py37
    dist: xenial
    sudo: true
cache:
  directories:
  - "$HOME/.cache/pip"
language: python
install: pip install -U tox-travis
script: travis_wait 30 tox --develop
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: awarecan
  password:
    secure: hXMeiNYzOAFKidhcaPKvOqLhtyzhvXKCfOGZ+JArpxT6tIxzlzuOxbouFkuKw7Qi8doWKpQv+IYU5t3S38PNzgasqa8jzQ41J1b0LB+u3Wds76BX+vWGIQWX+Nchs11K+IrCVFR9dBKN7i2T7TJQH9dlBgac4zCFjt3GAbTtOC5mVzV5jEMg4CRrzn/xC6BQ9xrasOZ8D5JJa6ygXb78tMUfpTrmx0LVybauHjHGsE4+F7yeCs34WcarHUeQCvucZ2uyhLEjguhuQVCDIN4jr2kY9XChyMS+aMFVhmPFg6uGnmrHh14zpmM0WOXW5f4ilOYJhvAhiir/rieQQUo5am1MGhqfY7XWqGJmnqDTE1OvZ7M+aiDkeBBzeMOXXfQxS8lCQLGrF/pOSioTj7CGRPfIlw/2ALwJg5GH/RnApTRIsSIN+rIGsRQFMkpfQ1w3KNQUV0mYIcPMehE8Xnl/8JWKINht4KGOC79NdfeMbwa15stGwWVlK9vhuXyxBp2oaaoOXqSBO6nrOKNotw5xmMR4W2/7Vq0jttEkzVkcEjTI47KKmitHsc7BI/njBNd78fCC6gnG7i/dJvtrpO4ksEIW8Z6BPlVPxLjXM4foml/XAzn/Aq0kIs7fmQ0Zeww6Zc8Uigz+4UTTFa4WtGzaQc9YHAPtoDcfi7M42YXHjPw=
  on:
    tags: true
    repo: rtfol/aiohttp-sse-client
    python: 3.6
