sudo: false
matrix:
  fast_finish: true
  include:
  - python: 3.5.3
    env: TOXENV=py35
  - python: '3.6'
    env: TOXENV=py36
  - python: '3.7'
    env: TOXENV=py37
    dist: xenial
    sudo: true
cache:
  directories:
  - "$HOME/.cache/pip"
language: python
install: pip install -U tox-travis
script: travis_wait 30 tox --develop
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: awarecan
  password:
    secure: EI/1E56RQqzbxaX+uqJ+Dq4PCz58H4hDtgeOgPlq+i4dg2dhAvMHkkQGMo2KRJ8aiIUWYALh3+05zYz8+K0tueO7h/F225T0zrA86V7LlCCUhGD4H3w3pMRgdUyEnqB7AL3fTxtm5HoT0RV4hblbt8yg/GwJOt2NtdmS21wF2i+K46a18RNEVAhGIcT4P4tg8e2efiLyX8gp2vusiyX6IpyPE0TYFqwuLXYlEnIt5e7/5UytkvnNwwpK62TPoqrlWmU9aXCQmv48Bdyipnlm/yvj8rTv8eSeuQVHiAzFgjk2tkNRe3oCImdFmR+4ChUsn4UBa+2T3d/t1MxObxcduuaPKObuTWHET+svrwSp4XDcq+2sVT2UmXC6IIxSZa8RbRUU25Gu/aZpjbqsSsCoqJ61fZwRhvXpXWwN9BVBgW0WQ0KO9nd+ClYX00aUGisZXvEIQSq2wALfoU6dYkLYnno8RXZUBbwlnGudyHd4+r1e5KuSGqPI6qZ8Mlwby8wbpdrwFEa5LiVKSL+fX+FIJsOHX30XH1XlkoTxLfFrTB+dmJFN+HcdOx4rRZ+Jib+3aoH451QQ7vv/IDNaLN6fZdRd3jBekRjpZHuCtrzDNofdyF76Z3UDcmUj/WFhKsh6FgxH1e2slyr2qxzxWWXZAfOL7Ox6P98PJjmI+fIhs3s=
  on:
    tags: true
    repo: rtfol/aiohttp-sse-client
    python: 3.6
